# Generated by Django 6.0.2 on 2026-02-08 23:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_paciente', models.CharField(choices=[('nuevo', 'Nuevo'), ('antiguo', 'Antiguo')], default='nuevo', max_length=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('clinico', 'Personal Clínico'), ('farmacia', 'Farmacia')], default='clinico', max_length=20)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('crear_paciente', 'Crear paciente'), ('crear_triaje', 'Crear triaje'), ('iniciar_atencion', 'Iniciar atención'), ('finalizar_atencion', 'Finalizar atención'), ('ver_historial', 'Ver historial'), ('generar_reporte', 'Generar reporte')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Triaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_consulta', models.DateTimeField(default=django.utils.timezone.now)),
                ('especialidad', models.CharField(choices=[('medicina_general', 'Medicina General'), ('pediatria', 'Pediatría'), ('ginecologia', 'Ginecología'), ('traumatologia', 'Traumatología'), ('cardiologia', 'Cardiología'), ('dermatologia', 'Dermatología'), ('neurologia', 'Neurología'), ('oftalmologia', 'Oftalmología'), ('otorrinolaringologia', 'Otorrinolaringología'), ('urologia', 'Urología'), ('psiquiatria', 'Psiquiatría'), ('emergencias', 'Emergencias')], max_length=50)),
                ('medico', models.CharField(max_length=100)),
                ('enfermeria', models.CharField(max_length=100)),
                ('talla', models.DecimalField(decimal_places=2, help_text='Talla en cm', max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5)),
                ('temperatura', models.DecimalField(decimal_places=2, help_text='Temperatura en °C', max_digits=4)),
                ('presion_arterial', models.CharField(help_text='Formato: 120/80', max_length=10)),
                ('pulsacion', models.IntegerField(help_text='Pulsaciones por minuto')),
                ('nivel_prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('estado', models.CharField(choices=[('en_espera', 'En Espera'), ('en_atencion', 'En Atención'), ('atendido', 'Atendido')], default='en_espera', max_length=20)),
                ('sintomatologia', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('estudios_complementarios', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triajes', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Triaje',
                'verbose_name_plural': 'Triajes',
                'ordering': [models.Case(models.When(nivel_prioridad='alta', then=0), models.When(nivel_prioridad='media', then=1), models.When(nivel_prioridad='baja', then=2)), 'fecha_hora_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('medicamentos_dispensados', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones', to=settings.AUTH_USER_MODEL)),
                ('triaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atencion', to='core.triaje')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
