# Generated by Django 6.0.2 on 2026-02-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('crear_paciente', 'Crear paciente'), ('crear_triaje', 'Crear triaje'), ('iniciar_atencion', 'Iniciar atención'), ('finalizar_atencion', 'Finalizar atención'), ('ver_historial', 'Ver historial'), ('generar_reporte', 'Generar reporte'), ('eliminar_paciente', 'Eliminar paciente'), ('crear_usuario', 'Crear usuario'), ('editar_usuario', 'Editar usuario')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('personal', 'Personal Común')], default='personal', max_length=20),
        ),
    ]
