# Generated by Django 6.0.2 on 2026-02-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registroauditoria_accion_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('farmacia', 'Farmacia'), ('enfermeria', 'Enfermería'), ('doctor', 'Doctor')], default='enfermeria', max_length=20),
        ),
    ]
