# Generated by Django 6.0.2 on 2026-02-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='triaje',
            name='tipo_servicio',
            field=models.CharField(choices=[('consulta_externa', 'Consulta Externa'), ('laboratorio', 'Laboratorio'), ('internacion', 'Internación'), ('cirugia', 'Cirugía'), ('emergencia', 'Emergencia'), ('farmacia', 'Farmacia'), ('otro', 'Otro')], default='consulta_externa', max_length=20, verbose_name='Tipo de Servicio'),
        ),
    ]
